apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: us.gcr.io/kontrax/user-service:latest
          imagePullPolicy: Always
          command: [
            "./user-service",
            "--selector=static",
            "--server_address=:8080"
          ]
          env:
            - name: DB_HOST
              value: "postgres-user:5432"
            - name: DB_NAME
              value: "postgres"
            - name: DB_PASS
              value: "password"
            - name: DB_USER
              value: "postgres"
            - name: UPDATED_AT
              value: "Tue 20 Mar 2018 08:53:19 GMT"
          ports:
            - containerPort: 8080
              name: user-port
