apiVersion: v1
kind: Service
metadata:
  name: postgres-user
  labels:
    app: postgres-user
spec:
  ports:
    - name: postgres-user
      port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    role: postgres-user
