// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/estimate/estimate.proto

package go_micro_srv_estimate

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Estimate struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Customer             *Customer  `protobuf:"bytes,2,opt,name=customer,proto3" json:"customer,omitempty"`
	Estimator            *Estimator `protobuf:"bytes,4,opt,name=estimator,proto3" json:"estimator,omitempty"`
	Address              string     `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	City                 string     `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	State                string     `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	Zip                  string     `protobuf:"bytes,8,opt,name=zip,proto3" json:"zip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Estimate) Reset()         { *m = Estimate{} }
func (m *Estimate) String() string { return proto.CompactTextString(m) }
func (*Estimate) ProtoMessage()    {}
func (*Estimate) Descriptor() ([]byte, []int) {
	return fileDescriptor_948a43a01aaea33c, []int{0}
}

func (m *Estimate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Estimate.Unmarshal(m, b)
}
func (m *Estimate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Estimate.Marshal(b, m, deterministic)
}
func (m *Estimate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Estimate.Merge(m, src)
}
func (m *Estimate) XXX_Size() int {
	return xxx_messageInfo_Estimate.Size(m)
}
func (m *Estimate) XXX_DiscardUnknown() {
	xxx_messageInfo_Estimate.DiscardUnknown(m)
}

var xxx_messageInfo_Estimate proto.InternalMessageInfo

func (m *Estimate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Estimate) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *Estimate) GetEstimator() *Estimator {
	if m != nil {
		return m.Estimator
	}
	return nil
}

func (m *Estimate) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Estimate) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Estimate) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Estimate) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

type Customer struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Customer) Reset()         { *m = Customer{} }
func (m *Customer) String() string { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()    {}
func (*Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_948a43a01aaea33c, []int{1}
}

func (m *Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Customer.Unmarshal(m, b)
}
func (m *Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Customer.Marshal(b, m, deterministic)
}
func (m *Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customer.Merge(m, src)
}
func (m *Customer) XXX_Size() int {
	return xxx_messageInfo_Customer.Size(m)
}
func (m *Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Customer proto.InternalMessageInfo

func (m *Customer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Estimator struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Estimator) Reset()         { *m = Estimator{} }
func (m *Estimator) String() string { return proto.CompactTextString(m) }
func (*Estimator) ProtoMessage()    {}
func (*Estimator) Descriptor() ([]byte, []int) {
	return fileDescriptor_948a43a01aaea33c, []int{2}
}

func (m *Estimator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Estimator.Unmarshal(m, b)
}
func (m *Estimator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Estimator.Marshal(b, m, deterministic)
}
func (m *Estimator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Estimator.Merge(m, src)
}
func (m *Estimator) XXX_Size() int {
	return xxx_messageInfo_Estimator.Size(m)
}
func (m *Estimator) XXX_DiscardUnknown() {
	xxx_messageInfo_Estimator.DiscardUnknown(m)
}

var xxx_messageInfo_Estimator proto.InternalMessageInfo

func (m *Estimator) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Response struct {
	Created              bool        `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Estimate             *Estimate   `protobuf:"bytes,2,opt,name=estimate,proto3" json:"estimate,omitempty"`
	Estimates            []*Estimate `protobuf:"bytes,3,rep,name=estimates,proto3" json:"estimates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_948a43a01aaea33c, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetEstimate() *Estimate {
	if m != nil {
		return m.Estimate
	}
	return nil
}

func (m *Response) GetEstimates() []*Estimate {
	if m != nil {
		return m.Estimates
	}
	return nil
}

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_948a43a01aaea33c, []int{4}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Estimate)(nil), "go.micro.srv.estimate.Estimate")
	proto.RegisterType((*Customer)(nil), "go.micro.srv.estimate.Customer")
	proto.RegisterType((*Estimator)(nil), "go.micro.srv.estimate.Estimator")
	proto.RegisterType((*Response)(nil), "go.micro.srv.estimate.Response")
	proto.RegisterType((*GetRequest)(nil), "go.micro.srv.estimate.GetRequest")
}

func init() { proto.RegisterFile("proto/estimate/estimate.proto", fileDescriptor_948a43a01aaea33c) }

var fileDescriptor_948a43a01aaea33c = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x4a, 0x3b, 0x31,
	0x14, 0xc5, 0xff, 0xe9, 0x67, 0x7a, 0xff, 0xa5, 0xca, 0x45, 0x21, 0x54, 0xc4, 0x71, 0x56, 0x5d,
	0x45, 0xa8, 0x4b, 0xd1, 0x4d, 0x29, 0xdd, 0xc7, 0xbe, 0xc0, 0x38, 0x73, 0x91, 0x2c, 0x6a, 0x6a,
	0x92, 0x16, 0xf4, 0x69, 0x7c, 0x11, 0x1f, 0xc9, 0x77, 0x90, 0xa6, 0x4d, 0x0a, 0xea, 0xd0, 0xee,
	0xee, 0xc7, 0xf9, 0x5d, 0x4e, 0xce, 0x0c, 0x5c, 0x2e, 0xad, 0xf1, 0xe6, 0x86, 0x9c, 0xd7, 0x8b,
	0xc2, 0x53, 0x2a, 0x64, 0x98, 0xe3, 0xf9, 0xb3, 0x91, 0x0b, 0x5d, 0x5a, 0x23, 0x9d, 0x5d, 0xcb,
	0xb8, 0xcc, 0xbf, 0x18, 0xf0, 0xe9, 0xae, 0xc1, 0x01, 0x34, 0x74, 0x25, 0x58, 0xc6, 0x46, 0x3d,
	0xd5, 0xd0, 0x15, 0xde, 0x01, 0x2f, 0x57, 0xce, 0x9b, 0x05, 0x59, 0xd1, 0xc8, 0xd8, 0xe8, 0xff,
	0xf8, 0x4a, 0xfe, 0x79, 0x46, 0x4e, 0x76, 0x32, 0x95, 0x00, 0x7c, 0x80, 0xde, 0x6e, 0x6d, 0xac,
	0x68, 0x05, 0x3a, 0xab, 0xa1, 0xa7, 0x51, 0xa7, 0xf6, 0x08, 0x0a, 0xe8, 0x16, 0x55, 0x65, 0xc9,
	0x39, 0xd1, 0x0e, 0x8e, 0x62, 0x8b, 0x08, 0xad, 0x52, 0xfb, 0x37, 0xd1, 0x09, 0xe3, 0x50, 0xe3,
	0x19, 0xb4, 0x9d, 0x2f, 0x3c, 0x89, 0x6e, 0x18, 0x6e, 0x1b, 0x3c, 0x85, 0xe6, 0xbb, 0x5e, 0x0a,
	0x1e, 0x66, 0x9b, 0x32, 0x1f, 0x02, 0x8f, 0x5e, 0x7f, 0x3e, 0x37, 0xbf, 0x80, 0x5e, 0x72, 0xf2,
	0x6b, 0xf9, 0xc1, 0x80, 0x2b, 0x72, 0x4b, 0xf3, 0xe2, 0x68, 0xe3, 0xad, 0xb4, 0x54, 0x78, 0xda,
	0x2a, 0xb8, 0x8a, 0xed, 0x26, 0xb2, 0xf8, 0xac, 0x03, 0x91, 0xc5, 0xd4, 0x55, 0x02, 0xf0, 0x3e,
	0x45, 0x46, 0x4e, 0x34, 0xb3, 0xe6, 0x31, 0xf4, 0x9e, 0xc8, 0xfb, 0x00, 0x33, 0xf2, 0x8a, 0x5e,
	0x57, 0xe4, 0xfc, 0xf8, 0x93, 0xc1, 0x49, 0x54, 0x3d, 0x92, 0x5d, 0xeb, 0x92, 0x70, 0x0e, 0x83,
	0x49, 0x30, 0x9a, 0x3e, 0xf9, 0xa1, 0xfb, 0xc3, 0x3a, 0x41, 0xcc, 0x22, 0xff, 0x87, 0x73, 0xe8,
	0xcf, 0xc8, 0x47, 0xc2, 0xe1, 0x75, 0x0d, 0xb2, 0x37, 0x77, 0xc4, 0xd5, 0xa7, 0x4e, 0xf8, 0x6f,
	0x6f, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x58, 0x91, 0x99, 0xa8, 0xd8, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for EstimateService service

type EstimateServiceClient interface {
	CreateEstimate(ctx context.Context, in *Estimate, opts ...client.CallOption) (*Response, error)
	GetEstimates(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error)
}

type estimateServiceClient struct {
	c           client.Client
	serviceName string
}

func NewEstimateServiceClient(serviceName string, c client.Client) EstimateServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.estimate"
	}
	return &estimateServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *estimateServiceClient) CreateEstimate(ctx context.Context, in *Estimate, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "EstimateService.CreateEstimate", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *estimateServiceClient) GetEstimates(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "EstimateService.GetEstimates", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EstimateService service

type EstimateServiceHandler interface {
	CreateEstimate(context.Context, *Estimate, *Response) error
	GetEstimates(context.Context, *GetRequest, *Response) error
}

func RegisterEstimateServiceHandler(s server.Server, hdlr EstimateServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&EstimateService{hdlr}, opts...))
}

type EstimateService struct {
	EstimateServiceHandler
}

func (h *EstimateService) CreateEstimate(ctx context.Context, in *Estimate, out *Response) error {
	return h.EstimateServiceHandler.CreateEstimate(ctx, in, out)
}

func (h *EstimateService) GetEstimates(ctx context.Context, in *GetRequest, out *Response) error {
	return h.EstimateServiceHandler.GetEstimates(ctx, in, out)
}
